name: Feature request
description: Suggest an idea for Quick Switcher
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: Describe the use case rather than the implementation.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
    validations:
      required: false
